pipeline:
    build-kusd-testnet:
        image: node:10
        commands:
            - export KOWALA_NETWORK="kusd-testnet"
            - make install
            - make build
        when:
            branch: [develop]
    upload-kusd-testnet:
        image: plugins/s3
        acl: public-read
        region: "us-east-1"
        bucket: "wallet.testnet.kowala.io"
        source: dist/**/*
        strip_prefix: dist
        target: /
        encryption: AES256
        when:
            branch: [develop]
    build-kusd-zygote:
        image: node:10
        commands:
            - export KOWALA_NETWORK="kusd-zygote"
            - make install
            - make build
        when:
            branch: [develop]
    upload-kusd-zygote:
        image: plugins/s3
        acl: public-read
        region: "us-east-1"
        bucket: "wallet.zygote.kowala.io"
        source: dist/**/*
        strip_prefix: dist
        target: /
        encryption: AES256
        when:
            branch: [develop]
